# Generated by Django 3.1.3 on 2020-12-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
