# Generated by Django 3.1.4 on 2020-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0005_auto_20201212_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
