# Generated by Django 3.1.4 on 2021-01-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0005_auto_20201212_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareusers',
            name='active',
        ),
    ]
