# Generated by Django 3.1.4 on 2021-01-06 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0005_auto_20201212_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PostReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rareserverapi.post')),
                ('reaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rareserverapi.reaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rareserverapi.rareusers')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(through='rareserverapi.PostReactions', to='rareserverapi.Reaction'),
        ),
    ]
