# Generated by Django 3.1.4 on 2020-12-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0006_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
