# Generated by Django 3.1.4 on 2021-01-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0007_auto_20210106_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='reaction_posts', related_query_name='reaction_post', through='rareserverapi.PostReactions', to='rareserverapi.Reaction'),
        ),
    ]
