# Generated by Django 3.1.4 on 2021-01-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0009_auto_20210106_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreactions',
            name='post',
        ),
    ]
