# Generated by Django 3.1.4 on 2021-01-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0006_remove_rareusers_active'),
        ('rareserverapi', '0012_auto_20210109_1548'),
    ]

    operations = [
    ]
