# Generated by Django 3.1.3 on 2021-01-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0013_merge_20210109_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscriptions', related_query_name='author_subscriptions', to='rareserverapi.rareusers')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_subscriptions', related_query_name='follower_subscriptions', to='rareserverapi.rareusers')),
            ],
        ),
    ]
