# Generated by Django 3.1.3 on 2021-01-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0014_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='ended_on',
            field=models.DateTimeField(null=True),
        ),
    ]
