# Generated by Django 3.1.3 on 2021-01-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0015_auto_20210113_0142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('follower_id', 'author_id')},
        ),
    ]
