# Generated by Django 3.1.3 on 2021-01-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareserverapi', '0017_auto_20210115_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_subscriptions', related_query_name='follower_subscriptions', to='rareserverapi.rareusers'),
        ),
    ]
